services:
  api:
    build: ./ai-writing-assistant-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers
    ports:
      - "8081:8000"   # <-- expone API en http://localhost:8081
    environment:
      - UVICORN_WORKERS=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./style-rewriter
    ports:
      - "8090:80"     # web en http://localhost:8090
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
